name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

env:
  IMAGE_NAME: kubectl
  PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: latest
            version: stable
          - tag: 1.26
            version: v1.26.1
          - tag: 1.25
            version: v1.25.6
          - tag: 1.24
            version: v1.24.10
          - tag: 1.23
            version: v1.23.16
          - tag: 1.22
            version: v1.22.17
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        id: buildx
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            quay.io/zenlab/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ matrix.tag }}
      - uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && matrix.version == 'stable') }}
        with:
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          context: .
          build-args: VERSION=${{ matrix.version }}
